version: "3"
services:
  employee-jdbc:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    networks:
      - mysql_db

  mysql_db:
    image: "mysql:8.0"
    ports:
      - 3307:3306
    networks:
      mysql_db:
    environment:
      MYSQL_DATABASE: java_to_dev_app_db
      MYSQL_USER: java_to_dev
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN

networks:
  mysql_db:
